# Generated by Django 4.1.4 on 2023-07-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
    ]
